stabilizer:
  stabilizer_name: 'NoStability'
  stabilizer_params:
    no_stability: ""


binarizer:
  binarizer_name: 'NormalizedDilateErodeBinarizer'
  binarizer_params:
    diff_frame_threshold: 30
    dilate_kernel_size: [15, 15]
    erode_kernel_size: [2, 2]
    thickness: 5
    dilate_kwargs:
      iterations: 1

    erode_kwargs:
      iterations: 1


detector:
  detector_name: 'DetectionsFromContours'
  detector_params:
    bbox_format: 'yolo'
    bbox_col_names: ["xRelative","yRelative","width","height"]


foreground_estimator:
  foreground_estimator_name: 'MovingCameraForegroundEstimetor'
  foreground_estimator_params:
    num_models: 2
    block_size: 2
    var_init: 400.0
    var_trim: 25.0
    lam: 0.001
    theta_v: 2500.0
    age_trim: 30
    theta_s: 2
    theta_d: 6
    dynamic: False
    sensitivity: False  # 'mixed' , True or False
    suppress: True
    smooth: False
    probs_params:
      t_alpha: 0.7
      s_alpha: 0.7
      neighborhood_size: [ 5, 5 ]
