stabilizer:
  stabilizer_name: 'NoStability'
  stabilizer_params:
    no_stability: ""


binarizer:
  binarizer_name: 'SimpleThresholdBinarizer'



morphology:
  morphology_name: 'FrameSuppressionDilateErodeMorphology'
  morphology_params:
    dilate_kernel_size: [10, 10]
    erode_kernel_size:
    thickness: 5
    dilate_kwargs:
      iterations: 1
    
    erode_kwargs:
      iterations: 1


detector:
  detector_name: 'DetectionsFromContours'
  detector_params:
    bbox_format: 'yolo'
    bbox_col_names: ["xRelative","yRelative","width","height"]


foreground_estimator:
  foreground_estimator_name: 'lowbb'
  foreground_estimator_params:
    model_path: "weights/soi_checkpoint.ckpt"
    height: 512
    width: 640
    device: "cpu"
    ultrasmallnet: False


convert_to_gray: False

    