stabilizer:
  stabilizer_name: 'NoStability'
  stabilizer_params:
    no_stability: ""


binarizer:
  binarizer_name: 'NormalizedDilateErodeBinarizer'
  binarizer_params:
    dilate_kwargs:
      iterations: 1

    erode_kwargs:
      iterations: 1


detector:
  detector_name: 'DetectionsFromContours'
    

foreground_estimator:
  foreground_estimator_name: 'MovingCameraForegroundEstimetor'
  foreground_estimator_params:
    num_models: 2
    block_size: 2
    var_init: 400.0
    var_trim: 25.0
    lam: 0.001
    theta_v: 2500.0
    age_trim: 30
    theta_s: 2
    theta_d: 2
    calc_probs: True
    sensitivity: True  # 'mixed' , True or False
    suppress: True
    smooth: False
